---
title: "Scraping of eit portfolio"
author: "Orhan Aktas"
date: '2023-04-13'
output:   
    html_document:
      toc: yes
      number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  class.source = "bg-warning text-warning"
)
```

```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(rvest)
```

# Introduction
listing via going backward
```{r main, eval=FALSE, include=FALSE}

# initial page
first_page<-"https://www.eiturbanmobility.eu/startup/motiontag/"

# create the main tibble
names<-tibble(link = first_page)

# read html of the first page
html <- read_html(first_page)



for (x in 1:2) {

#startsup_load_column
next_page <- html %>%
                html_elements(".post_post a") |>
                html_attr('href') 

names<-names |> add_row(link = next_page)

html <- read_html(next_page)

}


#.prev_post a
```

listing via going forward
```{r main, eval=FALSE, include=FALSE}

first_page<-"https://www.eiturbanmobility.eu/startup/peregrine-technologies/"

names<-tibble(link = first_page)

# stops link
html <- read_html(first_page)



for (x in 1:100) {

#startsup_load_column
next_page <- html %>%
                html_elements(".prev_post a") |>
                html_attr('href') 

names<-names |> add_row(link = next_page)

html <- read_html(next_page)

}



```

get_information

```{r main, eval=FALSE, include=FALSE}


page<-"https://www.eiturbanmobility.eu/startup/motiontag/"

# get name of the startup
startup<- substr( page,41, nchar(page)-1)

# read html
html <- read_html(page)

# get website of the startup
website<- html|>
                html_elements(".contact_web a") |>
                html_attr('href') 

# get country of the startup
country <- html|>
                html_elements(".col-xs-12:nth-child(3) .contact_mail") |> 
                html_text2()

# get main description of the startup
desc_main <- html|>
                html_elements("#post-8960 p:nth-child(1)") |>
                html_text2()

# get detailed description of the startup
desc_dtl <- html|>
                html_elements("#post-8960 p:nth-child(2)") |>
                html_text2()

# get second detailed description of the startup
desc_dtl2 <- html|>
                html_elements("#post-13522 p") |>
                html_text2()

# get participation year of the startup
partcpt_year<-html|>
                html_elements(".ass_year .contact_mail") |>
                html_text2()

# get associated hub
assct_hub<-html|>
                html_elements(".ass_region a") |>
                html_text2()

# get address of the startup
address<-html|>
                html_elements(".stup_cont_add") |>
                html_text2()

# get the year the startup founded
founded_date<-html|>
                html_elements(".col-md-3:nth-child(2) .contact_mail") |>
                html_text2()

# get contact email of the startup
contact<-html|>
                html_elements(".col-md-5 .contact_mail") |>
                html_text2()

# get associated program
programme<-html|>
                html_elements(".ass_programe a") |>
                html_text2()


# buradan aşağıda veriler ana tabloya koyulacak. alttakinde önce tablo yaratılıyor. sonrakinde ise satır eklenecek. ancak atama yapılmayan değişkenler boş olduğu için tibble ilk satırı eklemiyor. burada kaldım. 

# tam olarak şunu yapacağız. en son sayfada olan startup'ı buldum. buradaki sayfa. buradan verileri toplayarak geriye doğru gideceğiz. ileri doğru gitmemiz daha mantıklı olur sanki. sona bir startup eklenirse ileriye doğru giderken her zaman onu da almış oluruz.




# write all to the main table
names<- names |> add_row (
          startup=ifelse(identical(startup, character(0)),"",startup),
          page=ifelse(identical(page, character(0)),"",page),
          website=ifelse(identical(website, character(0)),"",website),
          country=ifelse(identical(country, character(0)),"",country),
          desc_main=ifelse(identical(desc_main, character(0)),"",desc_main),
          desc_dtl=ifelse(identical(desc_dtl, character(0)),"",desc_dtl),
          desc_dtl2=ifelse(identical(desc_dtl2, character(0)),"",desc_dtl2),
          partcpt_year=ifelse(identical(partcpt_year, character(0)),"",partcpt_year),
          assct_hub=ifelse(identical(assct_hub, character(0)),"",assct_hub),
          address=ifelse(identical(address, character(0)),"",address),
          founded_date=ifelse(identical(founded_date, character(0)),"",founded_date),
          contact=ifelse(identical(contact, character(0)),"",contact),
          programme=ifelse(identical(programme, character(0)),"",programme)
        )

```


create the main table
```{r}

names<- tibble (
          startup=character(),
          page=character(),
          website=character(),
          country=character(),
          desc_main=character(),
          desc_dtl=character(),
          desc_dtl2=character(),
          partcpt_year=character(),
          assct_hub=character(),
          address=character(),
          founded_date=character(),
          contact=character(),
          programme=character()
        )
```

