---
title: "Scraping of eit portfolio"
author: "Orhan Aktas"
date: '2023-04-13'
output:   
    html_document:
      toc: yes
      number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  class.source = "bg-warning text-warning"
)
```

```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(rvest)
```

# Introduction
listing via going backward
```{r main, eval=FALSE, include=FALSE}

# initial page
first_page<-"https://www.eiturbanmobility.eu/startup/motiontag/"

# create the main tibble
names<-tibble(link = first_page)

# read html of the first page
html <- read_html(first_page)



for (x in 1:2) {

#startsup_load_column
next_page <- html %>%
                html_elements(".post_post a") |>
                html_attr('href') 

names<-names |> add_row(link = next_page)

html <- read_html(next_page)

}


#.prev_post a
```

listing via going forward
```{r main, eval=FALSE, include=FALSE}

first_page<-"https://www.eiturbanmobility.eu/startup/peregrine-technologies/"

names<-tibble(link = first_page)

# stops link
html <- read_html(first_page)



for (x in 1:100) {

#startsup_load_column
next_page <- html %>%
                html_elements(".prev_post a") |>
                html_attr('href') 

names<-names |> add_row(link = next_page)

html <- read_html(next_page)

}



```

get_information

```{r main, eval=FALSE, include=FALSE}


page<-"https://www.eiturbanmobility.eu/startup/motiontag/"

# get name of the startup
startup<- substr( page,41, nchar(page)-1)

# read html
html <- read_html(page)

# get website of the startup
website <- html|>
                html_elements(".contact_web a") |>
                html_attr('href') 

# get country of the startup
country <- html|>
                html_elements(".col-xs-12:nth-child(3) .contact_mail") |> 
                html_text2()

# get main description of the startup
desc_main <- html|>
                html_elements("#post-8960 p:nth-child(1)") |>
                html_text2()

# get detailed description of the startup
desc_dtl <- html|>
                html_elements("#post-8960 p:nth-child(2)") |>
                html_text2()

# get second detailed description of the startup
desc_dtl2 <- html|>
                html_elements("#post-13522 p") |>
                html_text2()

# get participation year of the startup
partcpt_year<-html|>
                html_elements(".ass_year .contact_mail") |>
                html_text2()

# get associated hub
assct_hub<-html|>
                html_elements(".ass_region a") |>
                html_text2()

# get address of the startup
address<-html|>
                html_elements(".stup_cont_add") |>
                html_text2()

# get the year the startup founded
founded_date<-html|>
                html_elements(".col-md-3:nth-child(2) .contact_mail") |>
                html_text2()

# get contact email of the startup
contact<-html|>
                html_elements(".col-md-5 .contact_mail") |>
                html_text2()

# get associated program
programme<-html|>
                html_elements(".ass_programe a") |>
                html_text2()

# write all to the main table
names<-names |> add_row (
                  startup=startup,
                  page=page,
                  website=website,
                  country=country,
                  desc_main=desc_main,
                  desc_dtl=desc_dtl,
                  desc_dt2=desc_dt2,
                  partcpt_year=partcpt_year,
                  assct_hub=assct_hub,
                  address=address,
                  founded_date=founded_date,
                  contact=contact,
                  programme=programme
                )

```